Update BuildPublishRunTrackAvailablity.yml

diff --git a/.github/workflows/BuildPublishRunTrackAvailablity.yml b/.github/workflows/BuildPublishRunTrackAvailablity.yml
--- a/.github/workflows/BuildPublishRunTrackAvailablity.yml
+++ b/.github/workflows/BuildPublishRunTrackAvailablity.yml
@@ -50,6 +50,31 @@ jobs:
       run: |
         echo "DVCONNECTIONSTRING=${{ env.DVCONNECTIONSTRING }}" >> $GITHUB_ENV
         echo "AICONNECTIONSTRING=${{ env.AICONNECTIONSTRING }}" >> $GITHUB_ENV      
+
+    - name: Find the executable
+      id: find-executable-withconnections
+      run: |
+         set -e  # Exit immediately if a command exits with a non-zero status
+      
+         if [ -z "$DVCONNECTIONSTRING" ] || [ -z "$AICONNECTIONSTRING" ]; then
+         echo "Please provide the connection strings for Dataverse and Application Insights as an argument. (arg 1 = Dataverse, arg 2 = App Insights)"
+         exit 1
+         fi
+      
+         echo "DVCONNECTIONSTRING: $DVCONNECTIONSTRING"
+         echo "AICONNECTIONSTRING: $AICONNECTIONSTRING"
+      
+         cd D:\a\\Dataverse-Custom-Availability\\Dataverse-Custom-Availability\bin\Release || { echo "Failed to change directory"; exit 1; }
+      
+         dir || { echo "Failed to list directory contents"; exit 1; }
+      
+         if [ -f "./TrackAvailability.exe" ]; then
+         ./TrackAvailability.exe $DVCONNECTIONSTRING $AICONNECTIONSTRING || { echo "Failed to execute TrackAvailability.exe"; exit 1; }
+         else
+         echo "TrackAvailability.exe not found"
+         exit 1
+         fi
+
     
     - name: Find the executable
       id: find-executable
